### ISSUE TITLE
Air transportation emissions (NEI) misaligned

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#1]
The NEI captures emissions from landings and takeoffs (LTO) which are assigned to airports in the NEI point dataset. In most cases, these would end up assigned to NAICS that would get assigned to 48A000 - Scenic and sightseeing transportation and support activities for transportation. Instead they should be assigned to Air Transportation (481000)

See NEI TSD: https://www.epa.gov/sites/production/files/2018-06/documents/nei2014v2_tsd_09may2018.pdf; section 3.2

Emissions from LTO are noted by specific SCCs, primarily 2275020000

**Comment by WesIngwersen** [comment]
@bl-young Transferred from USEEIO
This is here for a reminder once we get to bringing in NEI data

**Comment by bl-young** [comment]
This has been resolved with commit https://github.com/USEPA/flowsa/commit/1faa56fd70c8703e2e2ce43e1cc8ba52fb43aec4
