### ISSUE TITLE
XLRD issue.

### ISSUE THREAD

**Issue by melissagqc** [USEPA/flowsa#100]
File "C:\Users\MelissaC\Envs\flowsa\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported

Occurred when running --year 2012 --source EIA_CBECS_Land.

**Comment by WesIngwersen** [comment]
we are using `openpyxl` for the xlsx file type so this code needs to be updated to use that library

**Comment by catherinebirney** [comment]
Thanks @WesIngwersen

**Comment by catherinebirney** [comment]
@melissagqc Can you run the EIA_CBECS_Land FBA in the 'xlrd' branch and see if the error is fixed? Thanks!

**Comment by catherinebirney** [comment]
solved by updating pandas requirement to 1.3.2 and xlrd to 2.0.1
