### ISSUE TITLE
materialflowlist import error

### ISSUE THREAD

**Issue by catherinebirney** [USEPA/flowsa#111]
Running "CRHW_national_2017" returns error:

    import materialflowlist as mfl
ModuleNotFoundError: No module named 'materialflowlist'

@bl-young We need to add materialflowlist to package requirements/setup. Do you have a specific version? Or did you want to make this package an optional requirement?

**Comment by bl-young** [comment]
With the updated mapping process, fedelemflowlist and materialflowlist are not longer called directly from within flowsa, so this is actually in esupy.

Perhaps we should move requirements for both to esupy? There are no releases yet for materialflowlist, in the meantime we could wrap these with an `except ImportError`. The mapping for CRHW doesn't actually do anything yet...

**Comment by catherinebirney** [comment]
your commit fixed the error - I'll close this issue out and make a jira task to look into dropping the fedelemflowlist package from flowsa
