### ISSUE TITLE
log files saved with _None in filename

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#112]
If no git hash is identified, the log files are stored as e.g.,:
`CRHW_national_2017_v0.3_None.log`

When saving files in esupy there is a check first for this parameter before appending to the name.
https://github.com/USEPA/esupy/blob/main/esupy/processed_data_mgmt.py#L242-L243

**Comment by catherinebirney** [comment]
@mathewlchambers fixed with PR #141
