### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#120]
I believe the nested structure of the .py files leads to import issues
see: https://github.com/USEPA/flowsa/runs/3907368775?check_suite_focus=true

I think this can be resolved by including __inti__.py in each subdirectory (e.g. data_source_scripts)

https://sweetcode.io/python-file-importation-multi-level-directory-modules-packages/

**Comment by catherinebirney** [comment]
Ah ok, this might explain the import errors Andy got while testing. I'll look into it
