### ISSUE TITLE
flownames in EPA GHG fbas

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#124]
FlowNames stored in GHG fbas need to be corrected
Flownames in the GHGI generally are CO2, CH4, N2O for main gases

reported from stored fba files

examples:
in T_2_1: `Recent_Trends...`   this must be replaced with the gas name like above
in T_3_10: `CH4 Emissions from Stationary Combustion` should be `CH4`

These all need to be reviewed and fixed. 
fyi @catherinebirney

**Comment by catherinebirney** [comment]
@WesIngwersen @melissagqc 
There were some updates to the GHG files that are still in the melissa_dev branch that need to be pulled in. I know the 'Activity' columns were modified, will have to run that branch to see if the FlowNames were also modified

**Comment by WesIngwersen** [comment]
Resolved
