### ISSUE TITLE
Possible infinite loop in common.py

### ISSUE THREAD

**Issue by matthewlchambers** [USEPA/flowsa#138]
In `common.find_true_file_path()`, if the directory, filename, and extension do not combine into a valid path, and if removing chunks of the filename following `_` does not lead to a valid path (e.g. due to a typo, or an error in the directory or extension), the function can get stuck in an infinite loop.

**Comment by catherinebirney** [comment]
@matthewlchambers fixed the infinite loop with pull request #139
