### ISSUE TITLE
Underutilization of `.yaml`s

### ISSUE THREAD

**Issue by matthewlchambers** [USEPA/flowsa#148]
Raising this as an issue now for awareness and discussion. I think we are currently hardcoding too many things in the data source script `.py` files and not making enough use of the `.yaml` files. For example, information on how to modify the NEI data url for different years, or information on how columns should be renamed (again, I'm thinking about the NEI data source in particular at the moment) and how the renaming depends on the year, could be included as dicts in the `EPA_NEI.yaml` files.

One advantage of offloading this information to the `.yaml` files is that it should simplify the process of adding new data years (e.g. the 2020 NEI, or 2018 and 2019 EQUATES data).

I'm working on the FBA methods and scripts for the EQUATES data right now, and I'll link to them once I'm finished, by way of an example of what I'm thinking.

**Comment by matthewlchambers** [comment]
To this point, for the EQUATES data it would be extrememly helpful if I could pass the `.yaml` information to the calling and parsing functions. I see two possible ways to do this: 1.) Combine the `config` dict into `args` before passing it; 2.) Add `config` as an arg to all the calling and parsing functions. 1 is easier, 2 is more consistent with how other `source.py` function work (and we should probably be moving away from folding things into `args`). I lean toward 2, but I'm willing to go through and implement whichever option is preferred.

**Comment by catherinebirney** [comment]
I agree with method 2

**Comment by bl-young** [comment]
@matthewlchambers your option 2 above is implemented in #150 correct?

Once that gets pulled in I can refactor the NEI, EIA_MECS, and ghgrp yamls to consolidate that information.

**Comment by matthewlchambers** [comment]
@bl-young Yes, that's correct!

**Comment by bl-young** [comment]
Updates have been made for NEI, GHGI, and EIA_MECS. We can consider others as we need to update them. Should we close this issue for now?

**Comment by matthewlchambers** [comment]
> Updates have been made for NEI, GHGI, and EIA_MECS. We can consider others as we need to update them. Should we close this issue for now?

Sorry, didn't see your comment until now. Yes, I think it can be closed.
