### ISSUE TITLE
add exception for missing url

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#152]
What is the case where the url_list is going to be empty?

Should this throw some kind of exception?

This check may be better off in `assemble_urls` or in `main()`

https://github.com/USEPA/flowsa/blob/e81ecbe9ccef9cc7a11f48387a146fc3abb88b39/flowsa/flowbyactivity.py#L124

**Comment by matthewlchambers** [comment]
Strictly speaking, the list won't be empty; it will have `'None'` as the first entry if the `source.py` file has `None` as the value for `url`. This is the case for several data sources, including the BEA data.

**Comment by matthewlchambers** [comment]
I'm not sure there's a better place for this check, as things stand, but I do suspect there might be a better way of dealing with data sets that don't have a url.

**Comment by bl-young** [comment]
right, ok makes sense to me. I'll close this.
