### ISSUE TITLE
URL concatentation missing '&' when forming Quickstats

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#166]
When indirectly calling on the code to generate the FBA for the CoA Cropland, it creates this URL where the xxxx is a valid API key

```
2022-01-11 10:50:10 INFO     Calling https://quickstats.nass.usda.gov/api/api_GET/?key=xxxxEsource_desc=CENSUS&sector_desc=ECONOMICS&statisticcat_desc=AREA%26statisticcat_desc%3DAREA+OPERATED&commodity_desc=AG+LAND%26commodity_desc%3DFARM+OPERATIONS&unit_desc=ACRES%26unit_desc%3DOPERATIONS&agg_level_desc=NATIONAL&year=2017
ERROR Error in URL request!
```
I can see that after the key value there is no ampersand to indicate the next URL parameter

**Comment by catherinebirney** [comment]
@WesIngwersen If you add the ampersand does the link work?
When I add an ampersand I get the error

**Comment by WesIngwersen** [comment]
ah i just assumed i didn't try it.. yes I get the same error. So something else is going on with that URL not working with the current API

**Comment by catherinebirney** [comment]
The url generation works in master. For some reason in the ghg branch spaces in the url are replaced with "+" while in the master branch spaces are replaced with "%20". I'm looking into the code changes in the ghg branch that modify url creation

**Comment by catherinebirney** [comment]
@bl-young @WesIngwersen The url error stems from the changes Ben linked. I fixed the issue for the USDA data, but need to recreate other FBAs before committing changes to make sure I don't break any other url imports

Wes, the USDA data are in the sharepoint folder if you want to skip FBA generation for now

**Comment by catherinebirney** [comment]
url error is fixed
