### ISSUE TITLE
consider moving methods to separate folder

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#168]
I find the methods can get a little bit lost within the `data` folder next to many of the other subfolders. Would it make sense to move [flowbysectormethods](https://github.com/USEPA/flowsa/tree/master/flowsa/data/flowbysectormethods) and [flowbyactivitymethods](https://github.com/USEPA/flowsa/tree/master/flowsa/data/flowbyactivitymethods) up a level into a folder called `methods`?

**Comment by catherinebirney** [comment]
@bl-young Yes, I agree the methods should be moved

**Comment by WesIngwersen** [comment]
Keeping in mind perhaps the consideration to make flowsa accept external methods and crosswalks.

**Comment by catherinebirney** [comment]
@bl-young @matthewlchambers @WesIngwersen 
I moved the fba/fbs methods and fbsactivitysets to a new methods directory in [3f651080](https://github.com/USEPA/flowsa/commit/3f651080c576be5fe758a82aefcdcbb943867d42) and [818e56d](https://github.com/USEPA/flowsa/commit/818e56d02f768e229b018dd4e921a4b9c0e8830d)
