### ISSUE TITLE
Permit user passed FBS YAML

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#172]
Allow flow-by-sector YAMLs to be kept outside of the package and passed for processing in a getFlowBySector() call. This will allow development of FBS methods outside of the main flowsa repo

**Comment by bl-young** [comment]
Currently running an FBS from an external method breaks the versioning scheme of the generated file, e.g.: `GHG_FBS_Example_ved3b801_ed3b801.parquet`

**Comment by catherinebirney** [comment]
I corrected the version number [ef5adc9](https://github.com/USEPA/flowsa/commit/ef5adc91dfeea13ecc7ec93b0cf292436e552604), but have not yet corrected that the git hash is generated by the repo the script is located, rather than flowsa's most recent hash
