### ISSUE TITLE
FBA `Unit` field format specs incorrectly require SI units

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#179]
I think our working method for FBA is to stick with the units in the source itself, correct? 

https://github.com/USEPA/flowsa/blob/develop/format%20specs/FlowByActivity.md

![image](https://user-images.githubusercontent.com/44471635/153616280-61fa66bb-803c-4427-8890-c91969f90a42.png)

**Comment by catherinebirney** [comment]
Thanks @bl-young corrected here [a0eb6b9](https://github.com/USEPA/flowsa/commit/a0eb6b94534834a9cd8da7e13aeac7ada679e3b2)
