### ISSUE TITLE
Identify changes in FBS results upon pull request

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#182]
With changes in code, we need to ensure that there are not unintended consequences to existing FBS.

Consider a gh_action to compare latest FBS on data commons with one generated with existing FBAs on data commons.

The goal is identify changes exclusively from changes in code.

**Comment by bl-young** [comment]
This has been initiated with a [new action](https://github.com/USEPA/flowsa/actions/workflows/compare_FBS_to_remote.yml) on the `fbs_action` branch. It required some adjustments to the package installation to ensure the necessary method files and supporting data are included on install.

**Comment by bl-young** [comment]
Currently one of the roadblocks is generating the necessary StEWI datasets upstream. While the stewicombo emissions files are sourced from data commons, the facility files which are also needed are not.

**Comment by bl-young** [comment]
@MoLi7 or @a-w-beck, I'm generating the files with the actions but am having trouble getting the path right to upload the artifact. 
See: https://github.com/USEPA/flowsa/runs/5416908251?check_suite_focus=true
Any ideas?

I'm printing out the path where its saved within the package [here](https://github.com/USEPA/flowsa/runs/5416908251?check_suite_focus=true#step:6:46) but I can't seem to get back to it

**Comment by MoLi7** [comment]
It looks like the file was save to the `flowsa` package installed under `/lib/python3.10/site-packages` instead of the `/data` folder in the repo, see https://github.com/USEPA/flowsa/runs/5416908251?check_suite_focus=true#step:6:46.
Could you try to replace `outdir` in https://github.com/USEPA/flowsa/blob/fbs_action/flowsa/test_FBS_against_remote.py#L16 with `/flowsa/data` in the repo?

**Comment by bl-young** [comment]
> It looks like the file was save to the `flowsa` package installed under `/lib/python3.10/site-packages` instead of the `/data` folder in the repo, see https://github.com/USEPA/flowsa/runs/5416908251?check_suite_focus=true#step:6:46.
> Could you try to replace `outdir` in https://github.com/USEPA/flowsa/blob/fbs_action/flowsa/test_FBS_against_remote.py#L16 with `/flowsa/data` in the repo?

yes, that `datapath` variable in flowsa is just the `/flowsa/data` folder within the package

I'm wondering if the pip install in this case manifests differently than how you set it up in R such that the package gets installed deep within site-packages but there is a copy of the repo more locally

**Comment by MoLi7** [comment]
Did you pip install flowsa in this case? If not, `checkout` ([this step](https://github.com/USEPA/flowsa/actions/runs/1931625408/workflow#L17)) should ensure the repo is cloned on gh runners, this is the same with how I set it up in R. I still think the issue is with `outdir`, maybe give it a try to not use `datapath` to set it up?

**Comment by bl-young** [comment]
I think its slightly different because we need to use the installed version not just run a script from the cloned repo. Either way, @a-w-beck and I were able to work through and figure out the path we needed to point to get to the data that gets hosted in the installed package
```
path: ${{ env.LD_LIBRARY_PATH }}/python3.10/site-packages/flowsa/data/fbs_diff/*_diff.csv
```

**Comment by MoLi7** [comment]
> I think its slightly different because we need to use the installed version not just run a script from the cloned repo. Either way, @a-w-beck and I were able to work through and figure out the path we needed to point to get to the data that gets hosted in the installed package
> 
> ```
> path: ${{ env.LD_LIBRARY_PATH }}/python3.10/site-packages/flowsa/data/fbs_diff/*_diff.csv
> ```

Oh I see. It makes sense that you need to use the installed version. Glad you guys figured out the correct path.

**Comment by bl-young** [comment]
@WesIngwersen , @catherinebirney 
[This action](https://github.com/USEPA/flowsa/actions/runs/1935983319) is now generating all FBS and comparing to data commons. Differences are logged in csv, downloadable as an artifact. This also then confirms that each FBS can be created successfully. Differences in FBS do not generate an error, but failure to generate the FBS will.

Take a look - I will do some additional formatting prior to generating a PR.
