### ISSUE TITLE
Error in generating USDA_CoA_Cropland_NAICS during water_national_2015_m2

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#184]
When generating water_national_2015_m2, the method generates an error during activity_set_4 when trying to generate USDA_CoA_Cropland_NAICS through the `disaggregate_pastureland` function.

https://github.com/USEPA/flowsa/blob/8d7b939695e7d3f70a16187ef8973975af7487d8/flowsa/data_source_scripts/USDA_IWMS.py#L146-L153

In line 146 year gets converted to a list.
[Note the logger shows the year as a list](https://github.com/USEPA/flowsa/runs/5415687848?check_suite_focus=true#step:6:1191). This impacts the [file_meta](https://github.com/USEPA/flowsa/blob/develop/flowsa/__init__.py#L50) needed to download and/or read the file

**Comment by catherinebirney** [comment]
Addressed with [8f874e6](https://github.com/USEPA/flowsa/commit/8f874e6e2e5223a6aa6b134936db25035f4ed3e8)
