### ISSUE TITLE
EIA MECS 2018 uses NAICS 2017 system

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#212]
I don't think we have `SectorSourceName` as a field for FBAs. I'm not yet sure exactly how we would consider the change in NAICS system, but the revised data reflects 2017 naics codes and not 2012

**Comment by catherinebirney** [comment]
@bl-young We do not have SectorSoureName in FBAs. We do have a[ function ](https://github.com/USEPA/flowsa/blob/develop/flowsa/validation.py#L651) that checks that sector-like columns are NAICS 2012 codes during FBS creation. We could add in the FBA description col that the data are NAICS 2017 and modify the validation function to convert NAICS 2017 to NAICS 2012 (if the sector source name in the FBS yaml is naics 2012). But we'll have to check if the conversion is 1 to 1 between the years.

**Comment by catherinebirney** [comment]
@bl-young Can we close this issue now that we specify NAICS year in source_catalog?

**Comment by bl-young** [comment]
yes fine by me
