### ISSUE TITLE
USGS_MYB url issues

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#217]
Many USGS Mineral Yearbook survey files are returning an access denied response even when accessing via browser

e.g. https://www.usgs.gov/centers/national-minerals-information-center/gold-statistics-and-information and select one of their older yearbook files

**Comment by catherinebirney** [comment]
@bl-young @melissagqc USGS MYB changed their urls, so we need to modify what we have in FLOWSA

**Comment by melissagqc** [comment]
There are 3 URLS that do not work for the years we are trying to access. These minerals are Copper, Phosphate, and Potash

**Comment by bl-young** [comment]
closing this in favor of tracking using #251
