### ISSUE TITLE
pandas.np deprecation

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#23]
Starting here and used in this function is pd.np.where
https://github.com/USEPA/flowsa/blob/72b7b186bfdc4bf290e840053e84135f6b74d265/flowsa/USGS_NWIS_WU.py#L105

Its throwing a warning of future deprecation. 
`FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead`

**Comment by catherinebirney** [comment]
modified function to np.where
