### ISSUE TITLE
One activity column requires direct allocation to sectors

### ISSUE THREAD

**Issue by catherinebirney** [USEPA/flowsa#235]
When both ActivityProducedBy and ActivityConsumedBy columns have values, one value must use "direct" allocation to sectors. FLOWSA is not designed to handle situations where both activities require additional allocation sources to attribute the activities to sectors. 

Will have to restructure how allocation is handled in FLOWSA to enable both activities to use allocation methods other than "direct."

**Comment by matthewlchambers** [comment]
One way we could handle that is just by dividing into activity sets based on one of the columns, then attributing each activity set based on the other column.

**Comment by catherinebirney** [comment]
Issue is resolved with recursive/sequential methodology introduced with flowsav2.0 - FBS methods can specify the activity column by which to attribute and can use sequential methodology to attribute each activity column with different attribution sources/methods
