### ISSUE TITLE
Updates to testing for improved clarity

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#249]
- [ ] Update filepath for csv download of data_diff (current lengthy folder structure)
- [ ] Move FBA config testing to its own job
- [ ] Post currently known failing FBAs to alert users and skip testing

**Comment by bl-young** [comment]
@catherinebirney do you want this to be added to v1.2.3?

**Comment by catherinebirney** [comment]
Sure, let's add it, but if these changes take more time than expected, we can push to the next release

**Comment by catherinebirney** [comment]
Addressed with #251
