### ISSUE TITLE
Memory error running FBS on ghgi-recursive-yaml/recursive-refac branches with pandas 1.5+

### ISSUE THREAD

**Issue by catherinebirney** [USEPA/flowsa#286]
pandas 1.5+ results in memory error and incomplete FBS generation. For now, generate FBS with < pandas 1.5 

@matthewlchambers @bl-young

**Comment by matthewlchambers** [comment]
I have tracked down the exact line in the `pandas 1.5.0` update that breaks my code. Now, I just have to figure out if there's a way to fix it and still ensure that column datatypes are correct.

**Comment by matthewlchambers** [comment]
The issue is that the `pandas` team added a call to the dataframe's constructor inside the builtin `astype()` method, and the `FlowBy` constructor includes a call to `astype()` to ensure the flowby has the correct data types. So it just loops over and over until it runs out of memory.
