### ISSUE TITLE
harmonized location system missing

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#290]
This is needed in .flowby, assuming we want it to be maintained,

https://github.com/USEPA/flowsa/blob/738f06aff1cf4cf55315d6213d91cddc3b2a1e5a/flowsa/dataclean.py#L242-L243

Without this update `compare_FBS_results()` will return all records as different.

Alternatively we could drop `LocationSystem` from the diff result, which could make sense anyway.

**Comment by bl-young** [comment]
see https://github.com/USEPA/flowsa/commit/1c803ee977ec88241b497ef4c89c8d2c00dee65e

**Comment by matthewlchambers** [comment]
With `compare_FBS_results()` no longer using `LocationSystem`, should we close this issue? It seems like a positive thing in general to retain this information, in case for some reason it's needed later.

**Comment by bl-young** [comment]
I guess the question remains whether the ultimate FBS should have `FIPS` (the old way) or `FIPS_2015` (the new way)

**Comment by matthewlchambers** [comment]
> I guess the question remains whether the ultimate FBS should have `FIPS` (the old way) or `FIPS_2015` (the new way)

Agreed. My vote is for `FIPS_2015`.

**Comment by catherinebirney** [comment]
I like FIPS_2015 - since we are already going to have to make changes in USEEIO to aggregate data, and accept new columns, we can add to that to-do list to drop "_year" from the LocationSystem

**Comment by matthewlchambers** [comment]
Going ahead and closing the issue.
