### ISSUE TITLE
Missing function disaggregate_usda_coa_cropland_naics

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#30]
https://github.com/USEPA/flowsa/blob/9a22cb0654c63737fa5367f2d1e387e29a86a141/flowsa/flowbysector.py#L38

>from flowsa.USDA_CoA_Cropland_NAICS import disaggregate_usda_coa_cropland_naics
>ImportError: cannot import name 'disaggregate_usda_coa_cropland_naics' from 'flowsa.USDA_CoA_Cropland_NAICS'

**Comment by WesIngwersen** [comment]
@catherinebirney i think this was probably just not pushed

**Comment by catherinebirney** [comment]
I wrote that function when I was figuring out method 2 for crop irrigation allocation - then decided to use a different allocation method. So disaggregate_usda_coa_cropland_naics does not exist and should not be called on in flowbysector. I'll remove the import call.
