### ISSUE TITLE
Estimate non-zero FlowAmounts when below source reporting threshold

### ISSUE THREAD

**Issue by matthewlchambers** [USEPA/flowsa#302]
The Aircraft row is missing from a newly generated `EPA_GHGI_T_3_14` FBA (year is 2016, if that matters).

**Comment by bl-young** [comment]
> I see that for 2016, that row is identified as being less than 0.05 MMT (specific value not given). Is that why it's excluded? If so, maybe there's a better way of handling that situation?

Yep that would be it. I do think your update to add a new field for that makes sense. In the current GHGI branch its not yet implemented.

**Comment by bl-young** [comment]
This is really something that needs to be implemented for each specific FBA. We have a few examples now where this is done:

EIA MECS:
https://github.com/USEPA/flowsa/blob/0d44ae9de372640d63926eb26208cbb31ec3665d/flowsa/data_source_scripts/EIA_MECS.py#L426-L432

Census SAS: https://github.com/USEPA/flowsa/blob/c18da34e36856ffb8aeebbbbc9ea07dee53e04fa/flowsa/data_source_scripts/Census_SAS.py#L66-L82

GHGI:
https://github.com/USEPA/flowsa/blob/56c6da4e03e0629c91b1e76a6ee727950e29fce3/flowsa/data_source_scripts/EPA_GHGI.py#L441-L460

The approach to handling of the suppressed data is then indicated in a FBS, for example this function for MECS:
https://github.com/USEPA/flowsa/blob/0d44ae9de372640d63926eb26208cbb31ec3665d/flowsa/data_source_scripts/EIA_MECS.py#L437-L458

**Comment by bl-young** [comment]
Going to close this issue as resolved knowing that this can be added to FBAs as they are updated.
