### ISSUE TITLE
Double counting of some flows in CNHWC_national

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#311]
Asphalt shingles and reclaimed asphalt pavement have a management pathway of "Other" in CDDPath. "Other" is also used as a APB designation. This is resulting in these two flows having extra quantities with the latest CDDPath (as of v1.3.0) for 236* and 237* as activity consumed by.

Net total increase in these flows is <1% of asphalt shingles and 6% for RAP.

**Comment by WesIngwersen** [comment]
</body>

</html>

**Comment by bl-young** [comment]
This is no longer an issue in v2.0
