### ISSUE TITLE
GHG_national_m1 FBS - year of MECS inconsistent

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#316]
2018 MECS data is used for allocation for data years 2017-2020 when MECS is used as the allocation source in most cases. However, for flows from EPA_GHG_T_3_22b, it appears that 2014 was used for these years

Source | FlowNames | AllocationSource | 2016 | 2017 | 2018 | 2019 | 2020
-- | -- | -- | -- | -- | -- | -- | --
EPA_GHGI_T_3_22 | Industry Asphalt & Road Oil, Industry Distillate Fuel Oil, Industry   HGL, Industry Lubricants, Industry Miscellaneous Products, Industry Naphtha   (<401 F), Industry Other Oil (>401 F), Industry Natural Gasoline,   Industry Petroleum Coke, Industry Special Naphtha, Industry Still Gas,   Industry Waxes | EIA_MECS_Energy |   |   |   |   | 2018
EPA_GHGI_T_3_22 | Industry Natural Gas to Chemical Plants | EIA_MECS_Energy |   |   |   |   | 2018
EPA_GHGI_T_3_22b | Industry Asphalt & Road Oil, Industry Distillate Fuel Oil, Industry   LPG, Industry Lubricants, Industry Miscellaneous Products, Industry Naphtha   (<401 F), Industry Other Oil (>401 F), Industry Pentanes Plus, Industry   Petroleum Coke, Industry Special Naphtha, Industry Still Gas, Industry Waxes | EIA_MECS_Energy | 2014 | 2014 | 2014 | 2014 |  
EPA_GHGI_T_3_22b | Industry Natural Gas to Chemical Plants | EIA_MECS_Energy | 2014 | 2014 | 2014 | 2014 |  
EPA_GHGI_T_3_8 | Coal Industrial - Manufacturing | EIA_MECS_Energy | 2014 | 2018 | 2018 | 2018 | 2018
EPA_GHGI_T_3_8 | Natural Gas Industrial - Manufacturing | EIA_MECS_Energy | 2014 | 2018 | 2018 | 2018 | 2018
EPA_GHGI_T_3_9 | Coal Industrial - Manufacturing | EIA_MECS_Energy | 2014 | 2018 | 2018 | 2018 | 2018
EPA_GHGI_T_3_9 | Natural Gas Industrial - Manufacturing | EIA_MECS_Energy | 2014 | 2018 | 2018 | 2018 | 2018
EPA_GHGI_T_A_5 | Industrial Other Coal Industrial - Manufacturing | EIA_MECS_Energy |   |   |   |   | 2018
EPA_GHGI_T_A_5 | Natural Gas Industrial - Manufacturing | EIA_MECS_Energy |   |   |   |   | 2018
EPA_GHGI_T_A_6 | Industrial Other Coal Industrial - Manufacturing | EIA_MECS_Energy |   |   |   | 2018 |  
EPA_GHGI_T_A_6 | Natural Gas Industrial - Manufacturing | EIA_MECS_Energy |   |   |   | 2018 |  
EPA_GHGI_T_A_7 | Industrial Other Coal Industrial - Manufacturing | EIA_MECS_Energy |   |   | 2018 |   |  
EPA_GHGI_T_A_7 | Natural Gas Industrial - Manufacturing | EIA_MECS_Energy |   |   | 2018 |   |  
EPA_GHGI_T_A_8 | Industrial Other Coal Industrial - Manufacturing | EIA_MECS_Energy |   | 2018 |   |   |  
EPA_GHGI_T_A_8 | Natural Gas Industrial - Manufacturing | EIA_MECS_Energy |   | 2018 |   |   |  
EPA_GHGI_T_A_9 | Industrial Other Coal Industrial - Manufacturing | EIA_MECS_Energy | 2014 |   |   |   |  
EPA_GHGI_T_A_9 | Natural Gas Industrial - Manufacturing | EIA_MECS_Energy | 2014 |   |   |   |  

</body>

</html>

Affects v1.3.1_a5c88ad  GHG FBS parquets

**Comment by bl-young** [comment]
@WesIngwersen, looking at the method dict that gets generated for 2017 in d019b5c, I think this should resolve this issue, but I haven't yet created the whole FBS
