### ISSUE TITLE
Split of HFCs leaves uncharacterized "Others"

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#325]
https://github.com/USEPA/flowsa/blob/4cf25930c7327d57f224166b75ce185adbcc3f59/flowsa/data_source_scripts/EPA_GHGI.py#L782

This fxn works to speciate the  "HFCs and PFCs" in  T_4_102 based on the breakdown in T_4_100, but this leaves the "Others" flows
![image](https://user-images.githubusercontent.com/5831306/220712297-044fe143-2bb1-4451-be93-64dbdc32d65c.png)

These "Others" flows do not get characterized later.   The CO2e of these Others is not-negligible - it is 9% of these ODS Substitutes CO2e in 2016 and 10% in 2017

**Comment by WesIngwersen** [comment]
I agree that it was lost before, but i think we should add it in as its included in the GHGI.  An option is to assigned it a proxy species

Here is some language from the GHGI 2022 4-137

_Others represent an unspecified mix of HFCs and PFCs, which includes HFC-152a, HFC-227ea, HFC-245fa, HFC-365mfc, HFC-43-10mee, HCFO-1233zd(E), HFO-1234yf, HFO-1234ze(E), HFO-1336mzz(Z), C4F10, and PFC/PFPEs, the latter being a proxy for a diverse collection of PFCs and perfluoropolyethers (PFPEs) employed for solvent applications. For estimating purposes, the GWP value used for PFC/PFPEs was based upon C6F14._

I don't think it implies that all the Others use the C6F14 CF, but C6F14 could potentially be used as a proxy. 

Would there be another option of including the CO2e from these Others?

**Comment by bl-young** [comment]
Two immediate options that come to mind are to either:
- map "Others" to something in the FEDEFL (we don't really have a great non-specific flow)
- or to `keep_unmapped_flows: True` to just leave it in the final FBS. Note the context and units would be different if there is no mapping:


Flowable | Class | SectorProducedBy | SectorConsumedBy | SectorSourceName | Context | Location | LocationSystem | FlowAmount | Unit | FlowType | Year
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
HFC-125 | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 1722.324 | kg | ELEMENTARY_FLOW | 2016
HFC-134a | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 6210.874 | kg | ELEMENTARY_FLOW | 2016
HFC-143a | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 810.8729 | kg | ELEMENTARY_FLOW | 2016
HFC-236fa | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 17.03279 | kg | ELEMENTARY_FLOW | 2016
HFC-32 | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 875.92 | kg | ELEMENTARY_FLOW | 2016
Others | Chemicals | 211111 |   | NAICS_2012_Code | air | 0 | FIPS | 0.001915 | MMT CO2e | ELEMENTARY_FLOW | 2016

**Comment by bl-young** [comment]
Ah yes saw your edit - we could do a generic CO2e flowable and add that to the flow list (per bullet 1 above)

**Comment by WesIngwersen** [comment]
`HFCs and PFCs, unspecified` perhaps with a MTCO2e unit?

**Comment by bl-young** [comment]
Yes I like that idea if you are ok with that flow.

**Comment by bl-young** [comment]
The units is going to be a challenge - mass units with CO2e is not a valid unit.

Could we call the flow `HFCs and PFCs, unspecified (CO2e)` and use units of kg?

**Comment by bl-young** [comment]
Will look something like this, pending final name:

Flowable | Class | SectorProducedBy | SectorConsumedBy | SectorSourceName | Context | Location | LocationSystem | FlowAmount | Unit | FlowType | Year
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
HFC-125 | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 1,722 | kg | ELEMENTARY_FLOW | 2016
HFC-134a | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 6,211 | kg | ELEMENTARY_FLOW | 2016
HFC-143a | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 811 | kg | ELEMENTARY_FLOW | 2016
HFC-236fa | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 17 | kg | ELEMENTARY_FLOW | 2016
HFC-32 | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 876 | kg | ELEMENTARY_FLOW | 2016
HFCs and PFCs, unspecified | Chemicals | 211111 |   | NAICS_2012_Code | emission/air | 0 | FIPS | 1,915 | kg | ELEMENTARY_FLOW | 2016
