### ISSUE TITLE
GHGI Table 3.9 errors

### ISSUE THREAD

**Issue by matthewlchambers** [USEPA/flowsa#333]
The GHGI table 3.9 has errors. Specifically, none of the "Natural Gas" activities (`Natural Gas Commercial`, `Natural Gas Industrial`, etc.) are coming through properly under `ActivityProducedBy`. Instead, `All activities Natural Gas` is repeated several times. These errors exist on the latest version I downloaded from the data commons (1.3.0).

**Comment by bl-young** [comment]
@catherinebirney can we put the 1.3.1 GHGI FBAs on data commons? This issue is resolved in the latest

**Comment by catherinebirney** [comment]
@matthewlchambers @bl-young v1.3.1 GHGI FBAs are on Data Commons
