### ISSUE TITLE
field burning activity mapping - NAICS resolution should be higher - 5 or 6?

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#368]
https://github.com/USEPA/flowsa/blob/2db51cfd74c11bfedb894000350826f47e9763d3/flowsa/data/activitytosectormapping/NAICS_Crosswalk_EPA_StateGHGI.csv?plain=1#L14C1-L14C1

Activity | SectorSourceName | Sector
-- | -- | --
Agriculture - Field   Burning of Agricultural Residues - Barley | NAICS_2012_Code | 1111
Agriculture - Field Burning of   Agricultural Residues - Chickpeas | NAICS_2012_Code | 1111
Agriculture - Field Burning of   Agricultural Residues - Cotton | NAICS_2012_Code | 1119
Agriculture - Field Burning of   Agricultural Residues - Dry Beans | NAICS_2012_Code | 1111
Agriculture - Field Burning of   Agricultural Residues - Grass Hay | NAICS_2012_Code | 1119
Agriculture - Field Burning of   Agricultural Residues - Legume Hay | NAICS_2012_Code | 1119

**Comment by bl-young** [comment]
The state models only go to 3 or 4 digit NAICS so I assume that's why we did it that way. We can make them more explicit and it shouldn't impact the final FBS (though in the future could help if we go more granular)

**Comment by WesIngwersen** [comment]
It would be inconsistent for one with the national method or general principles not too so I'm making those changes now. working from refac-recursive bit I will post to a branch off their for review

**Comment by WesIngwersen** [comment]
This issue applies to animal ag as well ...

https://github.com/USEPA/flowsa/blob/2db51cfd74c11bfedb894000350826f47e9763d3/flowsa/data/activitytosectormapping/NAICS_Crosswalk_EPA_StateGHGI.csv?plain=1#L6

**Comment by WesIngwersen** [comment]
@bl-young  punting this one to ERG to take over.    Please use EPA_GHGI mapping for reference mapping checks.

**Comment by bl-young** [comment]
collectively these result in no changes in FBS
