### ISSUE TITLE
Agriculture - Liming - CO2 emissions in state GHGI mapped incorrectly to manufacturing

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#369]
https://github.com/USEPA/flowsa/blob/2db51cfd74c11bfedb894000350826f47e9763d3/flowsa/data/activitytosectormapping/NAICS_Crosswalk_EPA_StateGHGI.csv?plain=1#L35

should be like in national GHGI mapping to ag

https://github.com/USEPA/flowsa/blob/2db51cfd74c11bfedb894000350826f47e9763d3/flowsa/data/activitytosectormapping/NAICS_Crosswalk_EPA_GHGI.csv?plain=1#L40

**Comment by bl-young** [comment]
I will reopen this as this will require selection of an attribution choice.

**Comment by bl-young** [comment]
2019 changes are as expected (aggregate across states):

Flowable | SectorProducedBy | FlowAmount_fbs1 | FlowAmount_fbs2 | FlowAmount_diff | Percent_Diff
-- | -- | -- | -- | -- | --
Carbon dioxide | 111 | 2.15E+10 | 2.25E+10 | 9.71E+08 | 4.52
Carbon dioxide | 112 | 1.96E+10 | 2.06E+10 | 9.71E+08 | 4.96
Carbon dioxide | 327 | 6.42E+10 | 6.22E+10 | -1.9E+09 | -3.03
