### ISSUE TITLE
"Commercial" mapped differently in stateGHGI and GHGI

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#370]
in stateGHGI mapping
https://github.com/USEPA/flowsa/blob/2db51cfd74c11bfedb894000350826f47e9763d3/flowsa/data/activitytosectormapping/NAICS_Crosswalk_EPA_StateGHGI.csv?plain=1#L61

the assignments to 2213 and 92* sectors are missing where they are present in the national model

https://github.com/USEPA/flowsa/blob/2db51cfd74c11bfedb894000350826f47e9763d3/flowsa/data/activitytosectormapping/NAICS_Crosswalk_EPA_GHGI.csv?plain=1#L156

https://github.com/USEPA/flowsa/blob/2db51cfd74c11bfedb894000350826f47e9763d3/flowsa/data/activitytosectormapping/NAICS_Crosswalk_EPA_GHGI.csv?plain=1#L172C14-L172C14

**Comment by bl-young** [comment]
`923` was added for CO2 eg.,
https://github.com/USEPA/flowsa/blob/2db51cfd74c11bfedb894000350826f47e9763d3/flowsa/data/activitytosectormapping/NAICS_Crosswalk_EPA_StateGHGI.csv#L92 
but I may have missed it for the CH4 activity set I will check.

**Comment by bl-young** [comment]
Expected changes, CH4 and N2O assigned to 923 pulled from other commercial sectors:
[comm_923.csv](https://github.com/USEPA/flowsa/files/12489693/comm_923.csv)

**Comment by bl-young** [comment]
Interpreting your reaction as approval on the 2213 @WesIngwersen  so closing this issue
