### ISSUE TITLE
Github Action Generate FBS Timeout

### ISSUE THREAD

**Issue by catherinebirney** [USEPA/flowsa#377]
We are generating too many FBS for the github action `Generate FBS` so the action fails when it times out

We need to revise the action - either drop some of the more time-intensive FBS or modify the code in another way

@bl-young

**Comment by catherinebirney** [comment]
The idea behind this function was to generate all FBS so we could upload those to Data Commons. But I generally run all the FBS locally because I generate new FBAs and this function downloads the FBAs from DC. Is it worth keeping this function? I'd be fine with deleting it, since our other FBS function that you revised checks that our methods work.

**Comment by bl-young** [comment]
yep agreed - probably not necessary

**Comment by catherinebirney** [comment]
We deleted generate_FBS.yml with [b79df8f](https://github.com/USEPA/flowsa/commit/b79df8fdfa904e3534c6a4e830908e578b9c6bc4)- this change will be pulled into master with the flowsa2.0 release
