### ISSUE TITLE
Error in green space ratio function

### ISSUE THREAD

**Issue by matthewlchambers** [USEPA/flowsa#384]
The `get_US_urban_green_space_and_public_parks_ratio` function in `literature_values.py` contains a `try . . . except` block that tries to catch a `ZeroDivisionError`. However, this error cannot be raised by the `try` block, since the `try` block only defines a function and doesn't actually do any division. Therefore, the desired behavior in the case of zero division will not occur.

**Comment by catherinebirney** [comment]
thanks @matthewlchambers - I'll look into this today

**Comment by catherinebirney** [comment]
@matthewlchambers Are you planning on using this data/function? Or is this a bug that you noticed and are flagging? I do not use that function in the land attribution method anymore, so I can delete it

**Comment by catherinebirney** [comment]
conclusion - delete fxn
