### ISSUE TITLE
map_to_BEA_sectors hardcoded for 2012

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#388]
https://github.com/USEPA/flowsa/blob/54addf713e11f426abce15d87c33662ac9220f28/flowsa/sectormapping.py#L164

Seems necessary to make this dynamic

**Comment by WesIngwersen** [comment]
Also this function, when being passed an fbs_collapsed, is returning two columns with 'Sector' name.

**Comment by catherinebirney** [comment]
Commit [d13fd1e](https://github.com/USEPA/flowsa/commit/d13fd1e2063b968aa62b7b8f3842de42208cf23b) lets us pick target bea year (default 2012), determines the naics year from the FBS itself, and drops duplicated Sector col
