### ISSUE TITLE
Equal attribution in electricity CO2 in m1?

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#390]
https://github.com/USEPA/flowsa/blob/c408987014b60628a6b9d1cc1386f338977d1d3d/flowsa/methods/flowbysectormethods/GHG_national_m2_common.yaml#L87C25-L87C39

Why is equal attribution used here?

**Comment by bl-young** [comment]
No attribution actually takes place as this sector is at the same granularity in m1 and m2 so this line is superfluous.
