### ISSUE TITLE
Missing county-level FIPS code

### ISSUE THREAD

**Issue by MoLi7** [USEPA/flowsa#4]
"02270" "46113" "51515" exist in BEA State Employment but not in /flowsa/data/FIPS.csv.
@WesIngwersen I will work with @catherinebirney to investigate this.

**Comment by catherinebirney** [comment]
@MoLi7 @WesIngwersen 
In 2015, "02270" and "46113" counties were renamed and assigned new FIPS ("02158" and "46102", respectfully). In 2013 "51515" was merged with "51019".

**Comment by MoLi7** [comment]
@catherinebirney @WesIngwersen 
Renaming FIPS can be problematic for processing state/county data like BEA State Employment data. I will see if I can pull BEA StateEmp with state name, otherwise, we might want to keep FIPS-State-County tables for different years.

**Comment by WesIngwersen** [comment]
We probably want to keep multiple FIPS years with mappings in between. I was thinking of changing the Fips field to A more generic Location with a LocationSystem field analogous to Other system fields. In this case we could have a LocationSystem like FIPS_2017.
