### ISSUE TITLE
Consider only allowing getFlowByActivity to take a single year and use an int

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#42]
This function as of now is just messy to send a list as opposed to a single year when we don't have any use cases for multiple years.
It would be just as easy for the user to call the function multiple times for multiple years (like in a loop) and concatenate.

If it takes a single year it will also be more consistent with getFlowBySector.

**Comment by catherinebirney** [comment]
@WesIngwersen - I agree, I'll modify the function

**Comment by WesIngwersen** [comment]
@catherinebirney please wait until after we pull in external_data which heavily transforms the __init__.py

**Comment by catherinebirney** [comment]
getFlowByActivity modified so year parameter is an integer and single year
