### ISSUE TITLE
Import error: No module named 'stewi.globals'; 'stewi' is not a package

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#47]
After installing with pip, attempting to access from flowsa: 
...
  File "C:\Users\cbirney\git_projects\flowsa\flowsa\stewi.py", line 31, in stewicombo_to_sector
    import stewicombo
  File "C:\Users\cbirney\AppData\Local\Programs\Python\Python37\lib\site-packages\stewicombo\__init__.py", line 5, in <module>
    from stewicombo.overlaphandler import aggregate_and_remove_overlap
  File "C:\Users\cbirney\AppData\Local\Programs\Python\Python37\lib\site-packages\stewicombo\overlaphandler.py", line 3, in <module>
    from stewi.globals import log
ModuleNotFoundError: No module named 'stewi.globals'; 'stewi' is not a package

It appears that duplicate globals.py could be causing an issue here?
cc: @catherinebirney

**Comment by WesIngwersen** [comment]
A potential problem I see with this stewi.py module is the use of the import statements within functions instead of making them global to the module.  I would suggest moving them out of the functions to the top and then seeing if this doesn't solve the issue

**Comment by bl-young** [comment]
I was concerned with having an import stewi command at the top, which would force an import of stewi or stewicombo even if not needed, and perhaps wasn't installed.

As another possible problem, it seems that naming this file stewi.py could also be causing confusion. http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap 

Perhpas this could be called stewiFBS.py or something

**Comment by catherinebirney** [comment]
@WesIngwersen @bl-young I renamed stewi.py in flowsa (only locally so far) which resolved the error
