### ISSUE TITLE
Add stewi requirement to setup and requirements

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#52]
Since stewi is called it needs to be added. See the fedelemflowlist example for how to add a github package. Make sure the specific release is specified and not a >=.

**Comment by bl-young** [comment]
I wonder if something like an [optional requirement](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies) would be more appropriate using `extras_require` since StEWIis only needed in some FBS.

**Comment by WesIngwersen** [comment]
Yes @bl-young I agree that this is a good approach - an optional requirement. We have to figure out how to document that.

**Comment by catherinebirney** [comment]
@bl-young I looked into using `extras_require` - from what I can tell it is generally used if there are sub-packages within a package (so like what you are doing with standardizedinventories). Given how flowsa is set up and how StEWI is integrated into flowbysector.py, I think the best approach is to make StEWI a requirement. Let me know what you think.

**Comment by bl-young** [comment]
I'm fine with that. the v1.0 release of stewi will be much slimmer so its less necessary to avoid having it as a requirement

**Comment by catherinebirney** [comment]
Added stewi to requirements
