### ISSUE TITLE
Datachecks expecting files in output folder for comparison

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#59]
Error occurs here
https://github.com/USEPA/flowsa/blob/c6032b888d389cc471aa62f35f1fb84c5480ddc9/flowsa/datachecks.py#L398

Flowbysector calls this function and it fails ..user would not be expected to have the file it looks for in  the output folder

**Comment by WesIngwersen** [comment]
This is the other case
https://github.com/USEPA/flowsa/blob/c6032b888d389cc471aa62f35f1fb84c5480ddc9/flowsa/flowbysector.py#L393

I'm commenting these calls to these functions in flowbysector now in my work in the external_data branch

**Comment by WesIngwersen** [comment]
Yet another is in
 check_allocation_ratios

**Comment by catherinebirney** [comment]
Okay thanks, I'll look into the errors - These three functions don't call on any files found in the outputfolder, but they do save a csv to the output folder, which is likely the problem

**Comment by WesIngwersen** [comment]
Ah yes, correct, thanks for clarifying that. I think we should just write those to the same output folder now controlled with that path object. You can help decide if they should be within the FlowBySector folder or another. If its s new folder then we have to assure that we create it before trying to write to it.

**Comment by catherinebirney** [comment]
I agree that the files should be stored in the local directory, in a folder other than FlowBySector. Right now they are stored in a folder called FlowBySectorMethodAnalysis

**Comment by catherinebirney** [comment]
modifed so files stored in local directory
