### ISSUE TITLE
Remove class param from flowbyactivity

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#60]
The class parameter and in a list format that is awkward and perhaps not necessary to have in fba.  We could easily remove the class requirement and users could apply a simple subset command if they wanted to get only one class.

**Comment by WesIngwersen** [comment]
@catherinebirney If flowbyactivity calls are being updated as part of the external_data calls, this could be done at the same time.

**Comment by catherinebirney** [comment]
@WesIngwersen We can make class a parameter in the FBS method yaml

**Comment by WesIngwersen** [comment]
> @WesIngwersen We can make class a parameter in the FBS method yaml

This issue refers to the init  getFlowByActivity method and not FBS

**Comment by catherinebirney** [comment]
I understand, I'm thinking through the implications changing getFlowByActivity will have on FBS.

What if we made class an optional parameter to getFlowByActivity? Otherwise we'll have to subset the dataframe every time it is called in FBS and it would be nice if that feature is already built in (like it is now)

**Comment by WesIngwersen** [comment]
Yes, I agree an optional parameter would make more sense.  Does it need to be list?  Ideally it could also be a string. I think calling functions with lists as parameters is just a bit awkward in the syntax. It would be possible to write a function that could take that optional parameter as  a string or multiple strings. I would recommend reviewing this post which has a nice discussion about best practices for such functions. https://stackoverflow.com/questions/51737078/python-allowing-passing-single-string-and-list-of-string-to-a-function/51737187

**Comment by catherinebirney** [comment]
Right now, we never call on more than one class at a time, so the parameter can be a string. Thanks for the stackoverflow link

**Comment by catherinebirney** [comment]
class parameter is optional and is a string rather than a list
