### ISSUE TITLE
USDA_CoA_Cropland has mixed flow classes

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#7]
The OPERATIONS flows are not a unit of Land, but rather of Other, so these should be stored in a separate parquet file. at this point flowsa doesn't support having more than one class stored together in a parquet. If that needs to change then we need to change source catalog to have a list for class instead of a string

**Comment by catherinebirney** [comment]
It makes more sense for Land and Other to be separate parquet files - I'll modify the code
