### ISSUE TITLE
Inconsistent use of source names

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/flowsa#8]
Ideally the sources need to be consistent across these uses:
in fba data 'SourceName' column 
in the file names of the parquet
in the Crosswalk file names
in the Source Catalog

The major issue is that we have generally have a  provider, an inventory/report, and a specific table or flow type.

**Comment by catherinebirney** [comment]
Thanks for pointing out this issue - I will modify the code

**Comment by WesIngwersen** [comment]
@catherinebirney wrote 
I think we should go with what we discussed a few hours ago [long names following a set pattern] regarding naming conventions. I like the current level of specificity of the data imports. There are four USDA datasets, three of which are CoA, but aggregating them to a higher level would make the data less intuitive, even though there is a shared API. There are several datasets with mixed flow class (CoA Cropland, CoA Livestock, EIA CBECS Water), but breaking the data imports into multiple parquets, based on flow class, would result in a larger, more cluttered output folder, without significant benefits. So I think we should modify the source catalog file to accommodate multiple flow class types and leave the data imports as-is. For consistency, we could modify the BLS and CBP imports, so employee count, establishment count, and payroll are in the same parquet.

**Comment by WesIngwersen** [comment]
@catherinebirney ok let's do that for now

**Comment by WesIngwersen** [comment]
@catherinebirney Please do post a list of proposed names and add the naming scheme to the main README so its clear for users and developers.

**Comment by catherinebirney** [comment]
Do you want me to post the proposed names in this thread?

**Comment by WesIngwersen** [comment]
sure

**Comment by catherinebirney** [comment]
Proposed Names:
1.   BLS_QCEW (modify so emp, estab, payann are in the same parquet)
2.   Census_CBP (modify so emp, estab, payann are in the same parquet)
3.   Census_Population
4.   EIA_CBECS_Water
5.   StatCan_IWS_WU (modifed from Stat_Canada)
6.   USDA_CoA_Cropland
7.   USDA_CoA_Livestock
8.   USDA_CoA_ProdMarkValue
9.   USDA_IWMS
10. USGS_NWIS_WU (modified from USGS_Water_Use)

**Comment by WesIngwersen** [comment]
3. What is the name of the survey or report for this population estimate?
4. We should probably remove water and get additional data as well.
6-8. I assume these final names are OK for now.
9. Are we getting everything from this survey?

**Comment by catherinebirney** [comment]
3. Population Estimates Program (PEP)...so Census_PEP_Population
4. I agree
5. No, we aren't. We could use StatCan_IWS_MI (Statistics Canada, Industrial Water Survey, Manufacturing Industries)

**Comment by catherinebirney** [comment]
Regarding "EIA_CBECS_Water", I think we should keep "Water" in the name and import the "Energy" information as a separate dataset. This naming convention would follow the same logic as splitting the CoA data into "Cropland" and "Livestock".  Additionally, the CBECS water data only exists for 2012, while we will import energy data for multiple years.
