### ISSUE TITLE
Need warning when attempting to obtain data for unavailable year

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#82]
`fba = flowsa.getFlowByActivity(datasource="EIA_MECS_Energy", year=2017)`
returns a bad zip file error because 2017 doesn't exist for EIA_MECS

Perhaps flowbyactivity could check against the list of years in the [FBA yaml](https://github.com/USEPA/flowsa/blob/master/flowsa/data/flowbyactivitymethods/EIA_MECS_Energy.yaml#L14-L16). This would also help prevent errors when new data are released (e.g. 2018 for EIA_MECS) but not yet tested

**Comment by catherinebirney** [comment]
Added this enhancement - currently in fba_dev branch
