### ISSUE TITLE
Make FBA cleaning functions optional in yaml

### ISSUE THREAD

**Issue by bl-young** [USEPA/flowsa#95]
Currently these two parameters need to be set to None; if they are not present a KeyError is raised. As is done for some other parameters, the presence of these specs could be tested first. This would reduce unnecessary information in the FBS method files.

https://github.com/USEPA/flowsa/tree/master/flowsa/data/flowbysectormethods#source-specifications-in-fba-or-fbs-format

**Comment by catherinebirney** [comment]
recent pull into master drops the two parameters
